<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>qlikview-expression</string>
	</array>
	<key>name</key>
	<string>QlikView expressions file</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#yamlNewDocument</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#qvs</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#simpleField</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>qvs</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(\s)*def:</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.qlikview-expression</string>
						</dict>
					</dict>
					<key>end</key>
					<string>((^(\s)*(name|label|title|):(\s)*)|^---$)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.qlikview-expression</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.qvs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>simpleField</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(^(\s)*(name|label|title):(\s)*)</string>
					<key>name</key>
					<string>support.constant.qlikview-expression</string>
				</dict>
			</array>
		</dict>
		<key>yamlNewDocument</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^---$</string>
					<key>name</key>
					<string>support.constant.qlikview-expression</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\.\.\.$</string>
					<key>name</key>
					<string>support.constant.qlikview-expression</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.qlikview-expression</string>
	<key>uuid</key>
	<string>6b77dc03-7003-41f4-a9f6-287849f88d4f</string>
</dict>
</plist>
