<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>qvw.log</string>
	</array>
	<key>name</key>
	<string>QlikView reload log file</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.qvs</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.qvw.log</string>
	<key>uuid</key>
	<string>6b77dc03-7003-41f4-a9f6-287849f88d4a</string>
</dict>
</plist>
