<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>qvw.log</string>
	</array>
	<key>name</key>
	<string>QlikView reload log file</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#assignment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#tableIdentifiers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#subroutine</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#log_line</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>assignment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.qvs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*([LlSs][Ee][Tt])\s+((\w|\.)+)\s*=</string>
				</dict>
			</array>
		</dict>
		<key>log_line</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^</string>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.line.qvw.log</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.qvs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>subroutine</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control.qvs</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.class</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^\s*([Ss][Uu][Bb])\s+((?:\w|\.)+)</string>
				</dict>
			</array>
		</dict>
		<key>tableIdentifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>support.constant.qvs</string>
						</dict>
					</dict>
					<key>match</key>
					<string>^(\s)*(\w+):(\s)*$</string>
					<key>name</key>
					<string>support.constant.qvs</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.qvw.log</string>
	<key>uuid</key>
	<string>6b77dc03-7003-41f4-a9f6-287849f88d4a</string>
</dict>
</plist>
