<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>qlikview-vars</string>
	</array>
	<key>name</key>
	<string>QlikView vars file</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#yamlNewDocument</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#definition</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expressionWithEqualSign</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#expressionWithoutEqualSign</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#simpleField</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>definition</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>(definition|macro):</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.qlikview-vars</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(^(?=(definition|label|comment|condition|background))|^---$)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.qlikview-vars</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.qvs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>expressionWithEqualSign</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(label|comment|condition|background):\s*(?==)</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.qlikview-vars</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(^(?=(definition|label|comment|condition|background))|^---$)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.qlikview-vars</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.qvs</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>expressionWithoutEqualSign</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>^(label|comment|condition|background):</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.qlikview-vars</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(^(?=(definition|label|comment|condition|background))|^---$)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>support.constant.qlikview-vars</string>
						</dict>
					</dict>
					<key>name</key>
					<string>string.single.quoted.qlikview-vars</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>name</key>
							<string>support.constant.qlikview-vars</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>simpleField</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(^(\s)*(set|let|tag):(\s)*)</string>
					<key>name</key>
					<string>support.constant.qlikview-vars</string>
				</dict>
			</array>
		</dict>
		<key>yamlNewDocument</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>^---$</string>
					<key>name</key>
					<string>support.constant.qlikview-vars</string>
				</dict>
				<dict>
					<key>match</key>
					<string>^\.\.\.$</string>
					<key>name</key>
					<string>support.constant.qlikview-vars</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.qlikview-vars</string>
	<key>uuid</key>
	<string>6b77dc03-7003-41f4-a9f6-287849f88d5f</string>
</dict>
</plist>
